# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  hwi_oauth.user.provider.entity:
    class: PelloBundle\Security\Provider\UserProvider
    arguments: ["@session", "@doctrine", "@admin.checker", "@request_stack"]
  admin.checker:
    class: PelloBundle\Security\Provider\AdminChecker
    arguments: ["@doctrine", "%admins%"]